server:
  port: 8087

spring:
  application:
    name: gateway-service

zuul:
  routes:
    user-service:
      path: /api/v2/**
      url: http://localhost:8082/api/v2/
    auth-service:
      path: /api/v1/auth/**
      url: http://localhost:8083/api/v1/auth/
    booking-service:
      path: /api/v1/**
      url: http://localhost:8081/api/v1/


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka