server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8083/
          predicates:
            - Path=/authenticate/**
        - id: user-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v2/**
        - id: booking-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka